[package]
name = "datalogic-rs"
version = "4.0.7"
edition = "2024"
exclude = [".DS_Store", "/target", ".vscode", ".github", "/docs", "/wasm"]
authors = ["Harishankar Narayanan <nharishankar@gmail.com>"]
license = "Apache-2.0"
description = "A fast, type-safe Rust implementation of JSONLogic for evaluating logical rules as JSON. Perfect for business rules engines and dynamic filtering in Rust applications."
readme = "README.md"
homepage = "https://github.com/GoPlasmatic/datalogic-rs"
repository = "https://github.com/GoPlasmatic/datalogic-rs"
keywords = ["rules", "engine", "json", "logic"]
categories = ["data-structures", "development-tools", "parsing"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4.42", default-features = false, features = ["std", "clock"] }
regex = { version = "1.12.2", default-features = false, features = ["std", "perf", "unicode"] }
smallvec = "1.15"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
